// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiTN69poMsHmphPU8TJDoWVFFMesZQizQ',
    appId: '1:223092437894:web:2a6db805c4368d927bf207',
    messagingSenderId: '223092437894',
    projectId: 'smartlock-be',
    authDomain: 'smartlock-be.firebaseapp.com',
    storageBucket: 'smartlock-be.firebasestorage.app',
    measurementId: 'G-B5DYJ24L6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpwSh_wvQ-OsZeE12ECeIyDX5CQi1jjws',
    appId: '1:223092437894:android:3fe72ba937ea88c17bf207',
    messagingSenderId: '223092437894',
    projectId: 'smartlock-be',
    storageBucket: 'smartlock-be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNYU6ZroLuWT2neUfPz2ipyYIBXBtE64',
    appId: '1:223092437894:ios:e20fe39fe3bfa13c7bf207',
    messagingSenderId: '223092437894',
    projectId: 'smartlock-be',
    storageBucket: 'smartlock-be.firebasestorage.app',
    iosBundleId: 'com.example.smartlockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNYU6ZroLuWT2neUfPz2ipyYIBXBtE64',
    appId: '1:223092437894:ios:e20fe39fe3bfa13c7bf207',
    messagingSenderId: '223092437894',
    projectId: 'smartlock-be',
    storageBucket: 'smartlock-be.firebasestorage.app',
    iosBundleId: 'com.example.smartlockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiTN69poMsHmphPU8TJDoWVFFMesZQizQ',
    appId: '1:223092437894:web:c800d93ccfef1a3d7bf207',
    messagingSenderId: '223092437894',
    projectId: 'smartlock-be',
    authDomain: 'smartlock-be.firebaseapp.com',
    storageBucket: 'smartlock-be.firebasestorage.app',
    measurementId: 'G-YW5YNQED5M',
  );
}
